### ISSUE TITLE
building on the commandline

### ISSUE THREAD

**Issue by jdkbx** [nthdimtech/signet-client#13] opened 2018-01-02 15:05 UTC
I want to package the signet-client for gentoo linux, so I need to build it on the command line. This seems quite rough right now. What I needed to do:

1. download signet-desktop-client sources and extract
2. download signet-firmware and extract
3. go to signet-firmware/signetdev and create build directory, enter it
4. run `qmake -qt=qt5 ../signetdev.pro` and `make`
5. create directory `signet-desktop-client/signet-firmware/build-signetdev-x86_64/release`
6. copy build artifacts from `signet-firmware/signetdev/build` into `signet-desktop-client/signet-firmware/build-signetdev-x86_64/release`
7. create `signet-desktop-client/build` directory and enter it
8. run `qmake -qt=qt5 ../qtclient/qtclient.pro` and `make`

The link time dependency from the client to signetdev (-lsignetdev) is the complicated part, forcing a two step build process. In the firmware it seems that only
tests/button-press-test
tools/stage2-firmware-loader
link against it. The rest only includes the `signetdev/common/signetdev_common.h` header, which does not contain functions.

I am not sure how to proceed from here. Maybe splitting signetdev into its own library, maybe just coding up a complicated ebuild doing the 8 steps above. Any suggestions are welcome.

**Comment by nthdimtech** [comment] 2018-01-03 19:36
You seem to have missed the fact that "signet-firmware" is a submodule of "signet-desktop-client". Downloading the submodule via git should remove some of the complexity in the steps above. For distro packaging I think that making signetdev a shared library in a separate package is the right solution in the long term since the command line tool also uses the library. However I haven't yet established a versioning scheme for signetdev and the API has been changing relatively frequently so I don't think packaging signetdev is the right choice yet. For now I would go with building in static with some variant of the steps above.

**Comment by jdkbx** [comment] 2018-01-04 19:58
I am trying to build from your releases. Getting the source from git is also possible, but is hackish to handle in a package management system that relies on version numbers.

I just tried with the git version to see if things get any easier. What system (os) are you using to build? For me the included ct-ng version would not compile due to some dependency problem (gperf-3.1, I think). So I used the current ct-ng-1.23.0 on my system. That brought its own set of problems (1. no support for gcc-7.2, needed to switch to gcc-6.4; 2. changed config for ct-ng, needed to add `*SYSROOT*` by hand), but worked in the end. Then your build-deps.sh script fails because there is no git submodule for [libaeabi-cortexm0]( https://github.com/bobbl/libaeabi-cortexm0.git) and the make step in `libb64-1.2.1` is missing. After adding these, 4 binaries are created.
I was hoping that signetdev would be build in the process, but that was not the case.
The `signetdev.pro` file has no DESTDIR set, so the target is created in the current working directory. I assume your build environment creates `build-signetdev-x86_64/release` by default as you use this as path for linking in the client and the tools. 

I guess I wait for you to make signetdev into a shared library before playing around any further.

Great work so far! Can't wait to see this project mature.

**Comment by nthdimtech** [comment] 2018-01-04 21:24
It looks like you were trying to build the firmware and firmware loading tools. These aren't necessary for building the client or the command line tool. That said, I definitely need to work on having easily reproducible build steps for the firmware related targets. I run Slackware 14.2 64bit but I believe I have also build the firmware targets from a version of Linux Mint.

The repository should be called "signet-core" or "signet-base" and the Makefile you were trying to run should be in a "firmware" sub-directory. You could argue that the firmware related files should be in a separate repo but I wanted to make it easy to keep signetdev in sync with firmware changes. I plan to do this restructuring once I'm done dealing with critical issues. I'll probably add an option for a shared library build of signetdev then.

**Comment by nthdimtech** [comment] 2018-01-20 18:20
Building the desktop client from the command line should be much easier now. Instead of linking libsignetdev.a I just build it's source files in place as a part of the main build. I like the idea of leaving the door open to building libsignetdev separately but there is no immediate need.

You'll need gcrypt and gnupg now since they are used by the KeePass import feature. I presently link these in statically but it shouldn't be hard to change the linkage to shared for packaging.

**Comment by jdkbx** [comment] 2018-01-20 22:56
It is easier, as it is now a one step process on the working git tree. So far so good.

I would like to build from your source code release. This is not yet possible without manually downloading the git submodules. I would argue, that for a complete source code release, the required submodules should be included, which in turn might not be so simple for licensing issues (I have not looked into this). But in their current form they are incomplete.

I assume you try to make it as easy as possible for someone to build your sources. And you succeed with that on the working git tree. But the dependency on git submodules makes it hard to fit into the automation for building source code releases I rely on.

In any case, kudos for pushing on.

**Comment by nthdimtech** [comment] 2018-01-21 00:24
I'm not making any source releases by choice, they are made automatically on GitHub for every tag I push. Ill turn the github behavior off if I can. The only reason I can to think to make them myself is if the git repository becomes too large to clone in a reasonable time and I don't think it's near that point yet.

Is building from git discouraged in some circles? As I see it makes it easier to be confident that your building from the right source.

On January 20, 2018 2:56:45 PM PST, jdkbx <notifications@github.com> wrote:
>It is easier, as it is now a one step process on the working git tree.
>So far so good.
>
>I would like to build from your source code release. This is not yet
>possible without manually downloading the git submodules. I would
>argue, that for a complete source code release, the required submodules
>should be included, which in turn might not be so simple for licensing
>issues (I have not looked into this). But in their current form they
>are incomplete.
>
>I assume you try to make it as easy as possible for someone to build
>your sources. And you succeed with that on the working git tree. But
>the dependency on git submodules makes it hard to fit into the
>automation for building source code releases I rely on.
>
>In any case, kudos for pushing on.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-desktop-client/issues/13#issuecomment-359208678

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jdkbx** [comment] 2018-01-21 01:00
I suspected that the source releases were autogenerated.
I think this is a gentoo linux specific thing. The philosophy is to build everything from sources and continually update everything (rolling release), which gives great flexibility and avoids the library hell (or dll-hell) problems you sometimes encounter when you start building things from source on binary distributions. But to keep such a system consistent you need to manage compatibility which is strictly based on package versions. So the package management system knows that package x in version y needs dependency a in version b. One person usually creates and updates a kind of recipe of how a package is build and what dependencies are required and every user of the distribution enjoys automatic consistent upgrades. That is why I need complete source releases.
It is possible to build from git directly inside the package management commonly with a hackish version string replacement (such as version 9999), but I loose the consistency regarding dependencies and with that the automatic updates through the package management system. This means users have themselves take care of updates and changed dependencies.
One could argue that building directly from git would even be better in the future, as commit hashes are the ultimate definition of a specific version. But we are not yet this advanced.

**Comment by nthdimtech** [comment] 2018-01-21 01:38
The need to discretize a history into relatively small number versions for dependency resolution is clear. This doesn't seem incompatible with git to me though. You just need a way to associate version numbers and tags in the git repo which should be just some kind of very simple regex. Instead of downloading tarball program-a.b.c.tar.gz you clone repo "program" and checkout tag "a.b.c". If there is no way to get this to work cleanly with gentoo scripts then I'll create a separate issue to automate the creation of full source releases and close this issue out.

**Comment by jdkbx** [comment] 2018-01-21 01:45
This is exactly it. There is no clean way to achieve the automated git checkout with the gentoo package management yet. If you implement your suggested solution it will be much appreciated. Thank you.

**Comment by nthdimtech** [comment] 2018-01-21 02:00
Thanks for the info. Distributing source archives will also lower the barrier to people building it themselves if my static builds don't work for them.

I've created an issue for this on the repository for the website: https://github.com/nthdimtech/nthdimtech-site/issues/4 . I'll create the archive manually for the upcoming 0.9.8 release and automate it later.

**Closed as completed** 2018-01-21 02:00 UTC

**Comment by nthdimtech** [comment] 2018-01-21 08:44
I've resolved https://github.com/nthdimtech/nthdimtech-site/issues/4. See https://nthdimtech.com/signet/downloads/#source-code for a link to the first source archive w/submodules
