### ISSUE TITLE
KeePass import feature

### ISSUE THREAD

**Issue by amatter** [nthdimtech/signet-client#14] opened 2018-01-03 19:01 UTC
Hello,
I just received my signet keys, thanks.

The description on the "Signet crowd supply webpage" says: 
...  It will support import and export of login information into KeePass databases, and export of all data types to unenecrypted formats such as plaintext, CSV, XML, and JSON. ...

I did not find a possibility to import data from KeePass to signet yet (For me this was a major point to get a signet). 

- Will this feature come in a future signet-desktop-client version? 
- or did I just miss something?

thanks, regards

**Comment by nthdimtech** [comment] 2018-01-03 19:29
In the initial software releases update  (https://www.crowdsupply.com/nth-dimension/signet/updates/initial-software-releases)  I mentioned that KeePass integration was not yet complete. So far I have 
made a test routine in the client that successfully reads KeePass  database entries but I still need to writing the code that converts the  entries into Signet's format and transmits them. I will do this after 
the keyboard layout issue  (https://github.com/nthdimtech/signet-desktop-client/issues/9) is resolved as it affects about half of the backers.

**Comment by dumblob** [comment] 2018-01-05 11:33
Originally raised here https://github.com/nthdimtech/signet-firmware/issues/16 .

See also an equivalent issue for the CLI client: https://github.com/nthdimtech/signet-cli/issues/3 .

**Comment by nthdimtech** [comment] 2018-01-19 07:51
On the branch keepass-import I have a working KeePass import feature. Since I'm not a KeePass user I was only able to test it with a dummy database I created. Anyone willing to try it? Linux would be a preferred platform to start with since I could avoid having to build and statically link gcrypt and zlib.

**Comment by nthdimtech** [comment] 2018-01-20 09:51
I'm preparing release 0.9.8 which will include the KeePass import feature. I've made builds for MacOS and Windows that you can find here: https://nthdimtech.com/downloads/signet-releases/0.9.8/

I haven't made the GNU/Linux build yet but will do so tomorrow.

@amatter  Are you willing to give this a try? As I mentioned I've only tested with a small made up KeePass database and I'd like to get feedback from someone importing a real database before publishing to all.

**Comment by nthdimtech** [comment] 2018-01-20 18:15
GNU/Linux build is up now

**Comment by dragon788** [comment] 2018-01-21 05:51
I'll see if I can test this with my old keepass database and maybe try a dump of my LastPass to keepass to see how it goes. I'm really looking forward to testing out the cli to see how I can add entries programmatically via python/bash script while waiting on the `pass`/`gopass` integration.

**Comment by nthdimtech** [comment] 2018-01-21 06:00
>I'll see if I can test this with my old keepass database

How old are we talking about? I only added support for KeePass 2.x databases. 

> I'm really looking forward to testing out the cli to see how I can add entries programmatically via python/bash script

Unfortunately the CLI isn't that advanced yet. It only supports device management functions (essentially everything *except* operating on entries). The tricky thing is that I made a design decision up front that the device interface would read/write binary blobs for maximal flexibility. Most of the code that knows how to interpret the blobs is integrated with the desktop client. I have to move it into a common library before the command line tool can do what you're interested in. My plan is to I'll publish the CLI as is soon, work on pass integration, then go back to completing the CLI

**Comment by dumblob** [comment] 2018-01-21 10:13
I finally found some time to test the desktop client. I've compiled everything myself (it worked!), but after starting the desktop client prompted me, that there is no signet device connected and I could not test anything.

I didn't receive my signets yet, so I'm just asking myself whether there is any "debug" mode of the client which allows testing even without having signet connected? Or any emulation of the signet device (but this sounds thousand times more difficult than just a special mode of the signet client).

**Comment by nthdimtech** [comment] 2018-01-22 01:38
Signet really needs the ability to operate on a database outside of the device but it isn't there yet. See: https://github.com/nthdimtech/signet-desktop-client/issues/8

I actually think a device emulation will be the simplest way actually. It would emulate on the level of the USB interface or anything but instead at the level of the "signetdev" API. It might even be possible to reuse some code from the firmware to do it.

**Comment by nthdimtech** [comment] 2018-01-22 01:45
Just a warning, if you've downloaded the 0.9.8 release recently I've found it has a serious regression that causes new accounts and bookmarks to not show up in the list view. The records are written to the device and will show up when you restart the client. I've made a new release "0.9.8.1" and published it on the website.

**Comment by nthdimtech** [comment] 2018-01-24 09:35
I am going to assume that one or more people have had success with the feature so I'm going to close this for now.

**Closed as completed by nthdimtech** 2018-01-24 09:35 UTC
